# -*- coding: utf-8 -*-
"""Aula1_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YnQNBRqan2vHktwmSJqXpHsNS6qbYU13

**Python para análise de dados (Pandas)**
"""

#Começar com autorização ao Google drive em File - Mount Drive
#Importar a biblioteca pandas
import pandas as pd #para usar apenas a palavra pd e não pandas
#criar uma variavel para armazenar o conjuunto de dados (df)
#copiar o caminho do arquivo nos tres pontos do arquivo do lado esquerdo
#resolver os erros: digitar virgula e ver os parametros permitidos pra usar no csv:
#ignorar linhas co erros no error_bad_lines=False
#visualizar as cinco primeiras linhas com df.head e pode usar df.head(10) para 10 linhas
#separador em ; - tirar tb 
#df.rename para renomear as colunas
#

df = pd.read_csv("/content/drive/MyDrive/DataSets/Gapminder.csv", error_bad_lines=False, sep=";")

df.head()

df = df.rename(columns={"country":"País", "continent":"Continente", "year":"Ano", "lifeExp":"Expectativa de vida", "pop":"Pop Total", "gdpPercap":"PIB"})

df.head()

df.shape #3312 linhas e 6 colunas

df.columns

df.dtypes

df.tail() #ultimas linhas e tb df.tail(15)

df.describe()

df["Continente"].unique()

oceania = df.loc[df["Continente"] == "Oceania"] #atribuir variavel, localizar, e quer que continente seja igual a oceania pra aparecer só esse
oceania.head()

oceania["Continente"].unique() #confirmar que todos em oceania pertencem a oceania

df.groupby("Continente")["País"].nunique() #quantos paises em cada continente com nunique

df.groupby("Ano")["Expectativa de vida"].mean() #para cada ano, qual a expectativa de vida média

df["PIB"].mean()

df["PIB"].sum() #soma de todos na coluna PIB